### Q1

In [1]:
import numpy as np

### Q2

In [8]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


### Q3

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Q4

In [12]:
a = np.zeros(10); a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
a[4] = 1

In [14]:
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### Q5

In [16]:
z = np.arange(10,51); z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

### Q6

In [17]:
z[::-1]

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

### Q7

In [19]:
np.arange(9).reshape(1,3,3)

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

### Q8

In [22]:
np.diag(np.array([1,1,1]))

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Q9

In [29]:
np.random.randint(50, size=(27)).reshape(3,3,3)

array([[[15,  9, 12],
        [48, 30,  4],
        [36, 38, 41]],

       [[47, 10, 38],
        [39,  4, 35],
        [20, 22, 27]],

       [[41, 42,  0],
        [19, 37, 31],
        [36, 49, 44]]])

### Q10

In [34]:
p = np.random.randint(30, size=(100)).reshape(1,10,10); p

array([[[16, 22,  0, 28, 14, 12, 27,  8, 13, 16],
        [ 0, 22, 19,  5, 21, 26, 17, 15, 11,  8],
        [27, 12,  7, 17,  9, 19, 27,  2,  4, 22],
        [10, 23,  1, 16, 16, 16,  0, 28, 21,  2],
        [21, 17,  3, 27,  3, 18,  6, 15, 24, 13],
        [29, 19,  9, 23, 25, 24, 16,  6,  6, 12],
        [17,  2,  8,  9,  7, 26,  9,  2,  3,  7],
        [ 2, 18,  8, 10, 19, 28, 16, 15, 19, 25],
        [11, 16, 26,  3, 11, 28, 28, 27,  9,  4],
        [10, 28, 28, 27,  1, 17, 17, 24, 24, 13]]])

In [40]:
p.min()

0

In [38]:
p.max()

29

### Q11

In [62]:
np.diag(np.array([1,2,3,4]), -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### Q12

In [65]:
a = np.random.randint(12, size=(5)); a

array([6, 7, 8, 8, 0])

In [66]:
sum(a)

29

### Q13

In [67]:
a = np.random.randint(12, size=(5)); a

array([11,  6,  0,  7,  3])

In [68]:
a.mean()

5.4

### Q14