### Q1 : Importer le package numpy

In [3]:
import numpy as np

### Q2 : Afficher la version de numpy et la configuration

In [8]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


### Q3 : Créer un vecteur nul de taille 10

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [12]:
a = np.zeros(10); a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
a[4] = 1

In [14]:
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50

In [16]:
z = np.arange(10,51); z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [17]:
z[::-1]

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8

In [19]:
np.arange(9).reshape(1,3,3)

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

### Q8 : Créer une matrice identié 3x3

In [22]:
np.diag(np.array([1,1,1]))

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Q9 : Créer une matrice 3x3x3 avec des valeurs random

In [29]:
np.random.randint(50, size=(27)).reshape(3,3,3)

array([[[15,  9, 12],
        [48, 30,  4],
        [36, 38, 41]],

       [[47, 10, 38],
        [39,  4, 35],
        [20, 22, 27]],

       [[41, 42,  0],
        [19, 37, 31],
        [36, 49, 44]]])

### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [94]:
p = np.random.randint(30, size=(100)).reshape(1,10,10); p

array([[[14, 19,  4, 16, 18,  8,  8, 13,  5, 15],
        [23, 12, 25, 13, 14,  3, 12,  9, 12, 19],
        [18,  7, 20, 19, 25,  5, 29,  9,  5, 22],
        [11,  0,  7,  6, 25,  5, 14,  3,  2, 22],
        [ 3, 20, 16,  2, 12,  5,  4,  7, 17, 12],
        [ 5,  0,  4, 11,  2, 23,  1,  3, 25, 10],
        [27, 23,  9, 17, 28, 18, 15, 29,  6, 20],
        [ 5, 19, 26, 23, 28, 23, 12, 14, 24,  1],
        [19, 19,  9, 21, 15, 19,  2, 11,  9,  9],
        [ 7, 24, 12, 24, 23,  1,  0, 15, 16,  8]]])

In [40]:
p.min()

0

In [38]:
p.max()

29

### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale

In [62]:
np.diag(np.array([1,2,3,4]), -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments

In [65]:
a = np.random.randint(12, size=(5)); a

array([6, 7, 8, 8, 0])

In [66]:
sum(a)

29

### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [67]:
a = np.random.randint(12, size=(5)); a

array([11,  6,  0,  7,  3])

In [68]:
a.mean()

5.4

### Q14 : En utilisant une fonction, donner la taille de la liste suivante :

In [5]:
l = [x for x in range(11)]; l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
np.shape(l)

(11,)

### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS

In [7]:
np.random.rand(10)

array([0.54746413, 0.95673541, 0.19760789, 0.81431996, 0.6219873 ,
       0.79603307, 0.35240005, 0.02700153, 0.96086889, 0.36640568])

### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [16]:
A= np.arange(5);A

array([0, 1, 2, 3, 4])

In [19]:
B = np.array([1,6,4,8,9]);B

array([1, 6, 4, 8, 9])

In [20]:
(A==B).all()

False

### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [36]:
A = np.random.randn(10); A

array([-0.94652616,  2.37622386, -0.97794473,  0.10052597, -0.02421811,
       -0.40066878, -0.8820519 ,  0.88642464,  0.20141906, -0.02601213])

In [37]:
A = A.astype(int)

In [38]:
A

array([0, 2, 0, 0, 0, 0, 0, 0, 0, 0])

### Q18 : Normaliser une matrice random 5x5¶
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type

In [89]:
A = np.random.randint(5, size=(25)).reshape(1,5,5); A

array([[[0, 2, 0, 3, 0],
        [3, 2, 1, 4, 3],
        [0, 2, 2, 4, 2],
        [2, 2, 0, 4, 4],
        [4, 2, 2, 4, 0]]])

In [91]:
(A - A.mean())/A.std()

array([[[-1.44444444, -0.05555556, -1.44444444,  0.63888889,
         -1.44444444],
        [ 0.63888889, -0.05555556, -0.75      ,  1.33333333,
          0.63888889],
        [-1.44444444, -0.05555556, -0.05555556,  1.33333333,
         -0.05555556],
        [-0.05555556, -0.05555556, -1.44444444,  1.33333333,
          1.33333333],
        [ 1.33333333, -0.05555556, -0.05555556,  1.33333333,
         -1.44444444]]])

### Q19 : Créer une matrice random M 2x2 et donner sa transposer
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes.

In [76]:
A = np.random.randint(6, size=(4)).reshape(2,2);A

array([[1, 5],
       [0, 4]])

In [79]:
A.transpose()

array([[1, 0],
       [5, 4]])

### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)