In [6]:
!pip install pandas numpy

You should consider upgrading via the 'c:\users\romai\appdata\local\programs\python\python38-32\python.exe -m pip install --upgrade pip' command.


In [7]:
!which python3

/c/Users/romai/AppData/Local/Microsoft/WindowsApps/python3


In [11]:
import numpy as np

In [9]:
l = [i for i in range(10)]

In [10]:
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [12]:
ar = np.array(l)

In [13]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
ar.argmax()

9

In [15]:
ar.min()

0

In [16]:
ar.mean()

4.5

In [14]:
ar.std()

2.8722813232690143

In [20]:
ar.dtype

dtype('int32')

### .Array convertit tout en unicode d'où le U11 (lorsqu'il y a plusieurs types différents au sain du même tableu)

In [22]:
ex = [1,2,3,'s']

In [23]:
np.array(ex)

array(['1', '2', '3', 's'], dtype='<U11')

In [28]:
m = np.array([[1,2],[3,4]]); m

array([[1, 2],
       [3, 4]])

In [29]:
m[0][1]

2

In [30]:
m[0][1] = 9

In [31]:
m

array([[1, 9],
       [3, 4]])

### .shape nous permet de connaître la dimension du tableau

In [32]:
m.shape

(2, 2)

In [34]:
m2 = np.array([1,2,3,4,5], ndmin=2); m2

array([[1, 2, 3, 4, 5]])

In [35]:
m2.shape

(1, 5)

In [36]:
m2

array([[1, 2, 3, 4, 5]])

### reshape permet de changer les lignes en colonnes et inversement

In [44]:
m2.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

### linspace pour comprendre ici on commence à 0 on va jusqu'à 2 et on veut le décomposer en 4 valeurs à distance égale

In [42]:
b = np.linspace(0,2,4)

In [43]:
b

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [45]:
b**2

array([0.        , 0.44444444, 1.77777778, 4.        ])

### ici reshape permet de trier le tableau dès sa création, on à donc 2 pour 2 dimensions, 3 pour le nombre de lignes et 4 pour le nombre de colonnes (4x3x2 = 24 comme le nombre de valeur, il faut retomber sur le même nombre de valeur)

In [56]:
c = np.arange(24).reshape(2,3,4); c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### .ndim nous donne le nombre de dimensions

In [55]:
c.ndim

3

In [53]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]]); ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
# ligne 2 et 3 et colonnes 1 et 2
ar[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [68]:
# juste la 2ème ligne et un tableau à une dimension
ar[1,:]

array([4, 5, 6])

In [69]:
#la dernière colonne
ar[:,-1]

array([3, 6, 9])

In [70]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
A,B

(array([[1, 1],
        [0, 1]]),
 array([[2, 0],
        [3, 4]]))

In [71]:
A+B

array([[3, 1],
       [3, 5]])

### argmax permet de connaître la position où se situe la valeur maximal

In [72]:
a = np.array([1.7,2.8,3])

In [73]:
a.argmax()

2

### le paramètre axis permet de calculer les lignes ou les colonnes sum(axis=0) si on veut additionner les colonnes sum(axis=1) si on veut additionner les lignes

In [74]:
b = np.array([[1,2],[3,4]])

In [75]:
b

array([[1, 2],
       [3, 4]])

In [76]:
sum(b)

array([4, 6])

In [77]:
b.sum(axis=0)

array([4, 6])

In [78]:
b.sum(axis=1)

array([3, 7])

In [79]:
np.array([1,2,3,4]).cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [80]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
np.arange(4,14,2)

array([ 4,  6,  8, 10, 12])

In [84]:
np.tile(3,8)

array([3, 3, 3, 3, 3, 3, 3, 3])

In [87]:
z =np.zeros((2,4)); z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [88]:
6*z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [89]:
np.ones((2,4), dtype='int8')

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [93]:
np.diag(np.array([1,4,5]))

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])